'use client';

import React from 'react';
import { useApp } from '../../context/AppContext';
import { LiveDemoSection } from '../../components/sections/LiveDemoSection';
import Link from 'next/link';
import { ArrowRight, Lock, FileCheck2 } from 'lucide-react';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';

export default function DemoPage() {
  const {
    runningScenario,
    scenarioResults,
    activeReceipt,
    pendingReviewReceipt,
    reviewActionLoading,
    runScenario,
    runAllScenarios,
    handleReviewAction,
  } = useApp();

  return (
    <div className="space-y-12">
      <div className="space-y-3 max-w-3xl">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-surface-card border border-border text-xs font-mono text-cyan-400">
          <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
          <span>Interactive Scenarios & Live Settlement</span>
        </div>
        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-white">
          Policy Decision Point Demo
        </h1>
        <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
          Evaluate 6 deterministic policy scenarios or execute a real devnet x402 payment settled through the public facilitator.
        </p>
      </div>

      <LiveDemoSection
        runningScenario={runningScenario}
        scenarioResults={scenarioResults}
        activeReceipt={activeReceipt}
        pendingReviewReceipt={pendingReviewReceipt}
        reviewActionLoading={reviewActionLoading}
        onRunScenario={async (sc) => {
          await runScenario(sc);
        }}
        onRunAllScenarios={runAllScenarios}
        onReviewAction={async (action) => {
          await handleReviewAction(action);
        }}
      />

      {/* Cross-navigation helpers */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-border/50">
        <Card className="p-5 bg-surface-card/80 border-border/80 flex items-center justify-between">
          <div className="space-y-1">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <Lock className="w-4 h-4 text-cyan-400" />
              Operator Mandates Console
            </h3>
            <p className="text-xs text-slate-400">
              Issue your own mandate with Phantom and test custom spending caps.
            </p>
          </div>
          <Link href="/mandates">
            <Button variant="outline" size="sm" className="text-xs">
              <span>Go to Mandates</span>
              <ArrowRight className="w-3 h-3 ml-1" />
            </Button>
          </Link>
        </Card>

        <Card className="p-5 bg-surface-card/80 border-border/80 flex items-center justify-between">
          <div className="space-y-1">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <FileCheck2 className="w-4 h-4 text-violet-400" />
              Signed Decision Receipts
            </h3>
            <p className="text-xs text-slate-400">
              Inspect the verifiable cryptographic receipts generated by your runs.
            </p>
          </div>
          <Link href="/receipts">
            <Button variant="outline" size="sm" className="text-xs">
              <span>View Receipts</span>
              <ArrowRight className="w-3 h-3 ml-1" />
            </Button>
          </Link>
        </Card>
      </div>
    </div>
  );
}
