'use client';

import React from 'react';
import { useApp } from '../../context/AppContext';
import { useWallet } from '../../context/WalletContext';
import { ActiveMandatesSection } from '../../components/sections/ActiveMandatesSection';
import Link from 'next/link';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { ArrowRight, Play, FileCheck2 } from 'lucide-react';

export default function MandatesPage() {
  const {
    publicKey,
    isConnected,
    openModal,
  } = useWallet();

  const {
    mandates,
    mandatesLoading,
    fetchMandates,
    showAllMandates,
    toggleShowAllMandates,
    revokingId,
    handleRevokeMandate,
    showIssuePanel,
    toggleIssuePanel,
    inMemoryAgent,
    mandateMaxPerTx,
    setMandateMaxPerTx,
    mandateTotalCap,
    setMandateTotalCap,
    mandateReviewThreshold,
    setMandateReviewThreshold,
    issueLoading,
    issueStatusText,
    issueError,
    handleSignAndIssueMandate,
    userIssuedMandate,
    userTestRunning,
    userTestResult,
    runUserMandateTest,
  } = useApp();

  return (
    <div className="space-y-12">
      <div className="space-y-3 max-w-3xl">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-surface-card border border-border text-xs font-mono text-cyan-400">
          <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
          <span>Operator Policy Console</span>
        </div>
        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-white">
          Operator Mandates
        </h1>
        <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
          Issue scoped spending allowances to autonomous agents with mutual Ed25519 signatures, monitor active caps, and revoke authority instantly.
        </p>
      </div>

      <ActiveMandatesSection
        mandates={mandates}
        mandatesLoading={mandatesLoading}
        revokingId={revokingId}
        onRefresh={() => fetchMandates()}
        onRevoke={handleRevokeMandate}
        showAllMandates={showAllMandates}
        onToggleShowAll={toggleShowAllMandates}
        showIssuePanel={showIssuePanel}
        onToggleIssuePanel={toggleIssuePanel}
        phantomPubkey={publicKey}
        isPhantomConnected={isConnected}
        onConnectPhantom={openModal}
        inMemoryAgent={inMemoryAgent}
        mandateMaxPerTx={mandateMaxPerTx}
        setMandateMaxPerTx={setMandateMaxPerTx}
        mandateTotalCap={mandateTotalCap}
        setMandateTotalCap={setMandateTotalCap}
        mandateReviewThreshold={mandateReviewThreshold}
        setMandateReviewThreshold={setMandateReviewThreshold}
        issueLoading={issueLoading}
        issueStatusText={issueStatusText}
        issueError={issueError}
        onSignAndIssueMandate={handleSignAndIssueMandate}
        userIssuedMandate={userIssuedMandate}
        userTestRunning={userTestRunning}
        userTestResult={userTestResult}
        onRunUserMandateTest={runUserMandateTest}
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-border/50">
        <Card className="p-5 bg-surface-card/80 border-border/80 flex items-center justify-between">
          <div className="space-y-1">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <Play className="w-4 h-4 text-cyan-400" />
              Scenario Runner
            </h3>
            <p className="text-xs text-slate-400">
              Run simulated agent requests against preconfigured mandates.
            </p>
          </div>
          <Link href="/demo">
            <Button variant="outline" size="sm" className="text-xs">
              <span>Go to Demo</span>
              <ArrowRight className="w-3 h-3 ml-1" />
            </Button>
          </Link>
        </Card>

        <Card className="p-5 bg-surface-card/80 border-border/80 flex items-center justify-between">
          <div className="space-y-1">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <FileCheck2 className="w-4 h-4 text-violet-400" />
              Receipts Explorer
            </h3>
            <p className="text-xs text-slate-400">
              Inspect all signed receipts generated by your mandates.
            </p>
          </div>
          <Link href="/receipts">
            <Button variant="outline" size="sm" className="text-xs">
              <span>View Receipts</span>
              <ArrowRight className="w-3 h-3 ml-1" />
            </Button>
          </Link>
        </Card>
      </div>
    </div>
  );
}
